import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { SWRConfig } from 'swr'
import { App } from './App'
import './index.css'

/** Follow the OS appearance, and keep following it if the user switches. */
function applyColourScheme(): void {
  const media = window.matchMedia('(prefers-color-scheme: dark)')
  const sync = (): void => {
    document.documentElement.classList.toggle('dark', media.matches)
  }
  sync()
  media.addEventListener('change', sync)
}

applyColourScheme()

/**
 * Deep links that arrive while the app is already open.
 *
 * Subscribed here rather than in a component: it belongs to the window, not to
 * anything React renders, and it has to be listening before the first paint so
 * a link that lands during startup is not dropped. The hash was generated by
 * the main process from a parsed route, so setting it here is not trusting the
 * link - see `main/deep-link.ts`.
 */
window.gitwarren.navigation.onDeepLink((hash) => {
  window.location.hash = hash
})

const container = document.getElementById('root')
if (!container) throw new Error('Root element is missing from index.html')

createRoot(container).render(
  <StrictMode>
    <SWRConfig
      value={{
        // Git state is read live, so coming back to the window should refresh
        // it - a branch may well have changed while you were in the terminal.
        revalidateOnFocus: true,
        revalidateOnReconnect: false,
        shouldRetryOnError: false
      }}
    >
      <App />
    </SWRConfig>
  </StrictMode>
)
